name: foundation_fluttify
description: Foundation for `Fluttify`.
version: 0.9.0-pre.10
author: yohom <yohombao@qq.com>
homepage: https://github.com/fluttify-project/foundation_fluttify

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.12.13 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: me.yohom.foundation_fluttify
        pluginClass: FoundationFluttifyPlugin
      ios:
        pluginClass: FoundationFluttifyPlugin